import { AgencyNav } from "@/components/AgencyNav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FileText, FolderKanban, ReceiptText, Upload } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type DocumentType = "contract" | "nda" | "sow";

async function toBase64(file: File) {
  const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("The PDF could not be read")); reader.readAsDataURL(file); });
  return dataUrl.split(",")[1] ?? "";
}

export default function AdminWorkspace() {
  const utils = trpc.useUtils();
  const clients = trpc.clients.list.useQuery(undefined, { retry: false });
  const projects = trpc.projects.list.useQuery(undefined, { retry: false });
  const documents = trpc.documents.list.useQuery(undefined, { retry: false });
  const dashboard = trpc.dashboard.overview.useQuery(undefined, { retry: false });
  const [project, setProject] = useState({ clientId: "", title: "", deadline: "", assignedTo: "" });
  const [document, setDocument] = useState({ clientId: "", projectId: "", title: "", type: "contract" as DocumentType });
  const [invoice, setInvoice] = useState({ clientId: "", dueAt: "", description: "", quantity: "1", unitAmount: "" });
  const projectCreate = trpc.projects.create.useMutation({ onSuccess: () => { utils.projects.list.invalidate(); utils.dashboard.overview.invalidate(); toast.success("Project created"); setProject({ clientId: "", title: "", deadline: "", assignedTo: "" }); }, onError: (error) => toast.error(error.message) });
  const documentCreate = trpc.documents.create.useMutation({ onSuccess: () => { utils.documents.list.invalidate(); toast.success("Document created"); setDocument({ clientId: "", projectId: "", title: "", type: "contract" }); }, onError: (error) => toast.error(error.message) });
  const invoiceCreate = trpc.invoices.create.useMutation({ onSuccess: () => { utils.dashboard.overview.invalidate(); toast.success("Invoice created and PDF stored"); setInvoice({ clientId: "", dueAt: "", description: "", quantity: "1", unitAmount: "" }); }, onError: (error) => toast.error(error.message) });
  const changeDocumentStatus = trpc.documents.setStatus.useMutation({ onSuccess: () => { utils.documents.list.invalidate(); toast.success("Document status updated"); }, onError: (error) => toast.error(error.message) });
  const changeInvoiceStatus = trpc.invoices.setPaymentStatus.useMutation({ onSuccess: () => { utils.dashboard.overview.invalidate(); toast.success("Invoice status updated"); }, onError: (error) => toast.error(error.message) });
  const fileUpload = trpc.files.upload.useMutation({ onSuccess: () => toast.success("PDF stored securely"), onError: (error) => toast.error(error.message) });
  const projectOptions = projects.data ?? [];
  const clientOptions = clients.data ?? [];
  const submitProject = () => { if (!project.clientId || !project.title) return toast.error("Client and project title are required"); projectCreate.mutate({ clientId: Number(project.clientId), title: project.title, deadlineAt: project.deadline ? new Date(project.deadline).getTime() : null, assignedTo: project.assignedTo || undefined }); };
  const submitDocument = () => { if (!document.clientId || !document.title) return toast.error("Client and document title are required"); documentCreate.mutate({ clientId: Number(document.clientId), projectId: document.projectId && document.projectId !== "none" ? Number(document.projectId) : null, title: document.title, documentType: document.type }); };
  const submitInvoice = () => { const quantity = Number(invoice.quantity); const unitAmountPaise = Math.round(Number(invoice.unitAmount) * 100); if (!invoice.clientId || !invoice.dueAt || !invoice.description || !Number.isInteger(quantity) || quantity < 1 || !Number.isFinite(unitAmountPaise)) return toast.error("Complete the invoice fields with a valid amount"); invoiceCreate.mutate({ clientId: Number(invoice.clientId), dueAt: new Date(invoice.dueAt).getTime(), gstPercent: 18, items: [{ description: invoice.description, quantity, unitAmountPaise }] }); };
  const submitPdf = async (file: File, documentId: number, clientId: number, isSigned: boolean) => { if (file.type !== "application/pdf") return toast.error("Only PDF files can be stored"); if (file.size > 10 * 1024 * 1024) return toast.error("PDF files must be 10 MB or smaller"); try { fileUpload.mutate({ clientId, documentId, fileKind: isSigned ? "signed_document" : "document_source", filename: file.name, contentType: "application/pdf", base64Data: await toBase64(file) }); } catch (error) { toast.error(error instanceof Error ? error.message : "The PDF could not be read"); } };
  return <div className="agency-app-shell"><AgencyNav /><main className="agency-main"><header className="agency-topbar"><div><p className="eyebrow">CEO workspace</p><p className="mt-1 text-xs text-[#748b82]">Brand Mint Studios</p></div></header><section className="pt-10 sm:pt-14"><p className="eyebrow">Operations</p><h1 className="mt-3 font-display text-4xl tracking-[-0.06em] text-[#102f25] sm:text-5xl">Manage the work.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#668078]">Create projects, prepare document records, and issue itemised invoices.</p><Tabs defaultValue="projects" className="mt-9"><TabsList className="grid h-auto w-full max-w-xl grid-cols-3 rounded-xl bg-[#eaf1ed] p-1"><TabsTrigger value="projects" className="gap-2 rounded-lg text-xs"><FolderKanban className="h-3.5 w-3.5" />Projects</TabsTrigger><TabsTrigger value="documents" className="gap-2 rounded-lg text-xs"><FileText className="h-3.5 w-3.5" />Documents</TabsTrigger><TabsTrigger value="invoices" className="gap-2 rounded-lg text-xs"><ReceiptText className="h-3.5 w-3.5" />Invoices</TabsTrigger></TabsList>
    <TabsContent value="projects" className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Create project"><SelectField label="Client" value={project.clientId} onValueChange={(value) => setProject({ ...project, clientId: value })} options={clientOptions.map((client) => ({ value: String(client.id), label: client.companyName }))} placeholder="Select client" /><Field label="Project title"><Input value={project.title} onChange={(event) => setProject({ ...project, title: event.target.value })} /></Field><Field label="Deadline"><Input type="date" value={project.deadline} onChange={(event) => setProject({ ...project, deadline: event.target.value })} /></Field><Field label="Assigned to"><Input value={project.assignedTo} onChange={(event) => setProject({ ...project, assignedTo: event.target.value })} /></Field><Button onClick={submitProject} disabled={projectCreate.isPending} className="mt-5 bg-[#103c2e] text-white hover:bg-[#0b3024]">Create project</Button></FormCard><RecordList title="Project records" records={projectOptions.map((item) => ({ id: item.project.id, title: item.project.title, detail: `${item.clientName} · ${item.project.status.replace("_", " ")}` }))} /></TabsContent>
    <TabsContent value="documents" className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Create document"><SelectField label="Client" value={document.clientId} onValueChange={(value) => setDocument({ ...document, clientId: value })} options={clientOptions.map((client) => ({ value: String(client.id), label: client.companyName }))} placeholder="Select client" /><SelectField label="Project" value={document.projectId} onValueChange={(value) => setDocument({ ...document, projectId: value })} options={projectOptions.map((item) => ({ value: String(item.project.id), label: item.project.title }))} placeholder="No project" optional /><SelectField label="Document type" value={document.type} onValueChange={(value) => setDocument({ ...document, type: value as DocumentType })} options={[{ value: "contract", label: "Contract" }, { value: "nda", label: "NDA" }, { value: "sow", label: "SOW" }]} placeholder="Document type" /><Field label="Document title"><Input value={document.title} onChange={(event) => setDocument({ ...document, title: event.target.value })} /></Field><Button onClick={submitDocument} disabled={documentCreate.isPending} className="mt-5 bg-[#103c2e] text-white hover:bg-[#0b3024]">Create document</Button></FormCard><div className="surface-card"><p className="eyebrow">Document records</p><div className="mt-5 space-y-2">{documents.data?.length ? documents.data.map((item) => <div key={item.id} className="rounded-xl border border-[#e3ece7] p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-[#35564a]">{item.title}</p><p className="mt-1 text-[11px] text-[#789087]">{item.documentType} · {item.status.replace("_", " ")}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => changeDocumentStatus.mutate({ id: item.id, clientId: item.clientId, status: "awaiting_signature" })}>Request signature</Button><Button size="sm" variant="outline" onClick={() => changeDocumentStatus.mutate({ id: item.id, clientId: item.clientId, status: "signed" })}>Mark signed</Button></div></div><Label className="mt-3 flex cursor-pointer items-center gap-2 rounded-lg bg-[#f4f8f5] px-3 py-2 text-[11px] font-bold text-[#547167]"><Upload className="h-3.5 w-3.5" />Store PDF<input className="sr-only" type="file" accept="application/pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) void submitPdf(file, item.id, item.clientId, item.status === "signed"); event.currentTarget.value = ""; }} /></Label></div>) : <Empty message="Document records will appear here." />}</div></div></TabsContent>
    <TabsContent value="invoices" className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Issue invoice"><SelectField label="Client" value={invoice.clientId} onValueChange={(value) => setInvoice({ ...invoice, clientId: value })} options={clientOptions.map((client) => ({ value: String(client.id), label: client.companyName }))} placeholder="Select client" /><Field label="Due date"><Input type="date" value={invoice.dueAt} onChange={(event) => setInvoice({ ...invoice, dueAt: event.target.value })} /></Field><Field label="Line item"><Textarea value={invoice.description} onChange={(event) => setInvoice({ ...invoice, description: event.target.value })} className="min-h-20" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Quantity"><Input value={invoice.quantity} onChange={(event) => setInvoice({ ...invoice, quantity: event.target.value })} inputMode="numeric" /></Field><Field label="Amount (INR)"><Input value={invoice.unitAmount} onChange={(event) => setInvoice({ ...invoice, unitAmount: event.target.value })} inputMode="decimal" /></Field></div><p className="text-[11px] leading-5 text-[#789087]">GST is calculated at the 18% rate stated for Brand Mint Studios ecommerce services.</p><Button onClick={submitInvoice} disabled={invoiceCreate.isPending} className="mt-2 bg-[#103c2e] text-white hover:bg-[#0b3024]">Issue invoice</Button></FormCard><div className="surface-card"><p className="eyebrow">Invoice records</p><div className="mt-5 space-y-2">{dashboard.data?.invoices.length ? dashboard.data.invoices.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#e3ece7] p-3"><div><p className="text-xs font-bold text-[#35564a]">{item.invoiceNumber}</p><p className="mt-1 text-[11px] text-[#789087]">{item.status} · INR {(item.totalPaise / 100).toLocaleString("en-IN")}</p></div>{item.status !== "paid" && item.status !== "void" ? <Button size="sm" variant="outline" onClick={() => changeInvoiceStatus.mutate({ id: item.id, clientId: item.clientId, status: "paid" })}>Mark paid</Button> : null}</div>) : <Empty message="Issued invoices will appear here with payment actions." />}</div></div></TabsContent></Tabs></section></main></div>;
}

function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="surface-card space-y-4"><p className="eyebrow">{title}</p>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#5e766d]">{label}</Label>{children}</div>; }
function SelectField({ label, value, onValueChange, options, placeholder, optional = false }: { label: string; value: string; onValueChange: (value: string) => void; options: { value: string; label: string }[]; placeholder: string; optional?: boolean }) { return <Field label={label}><Select value={value} onValueChange={onValueChange}><SelectTrigger><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{optional && <SelectItem value="none">No project</SelectItem>}{options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></Field>; }
function RecordList({ title, records }: { title: string; records: { id: number; title: string; detail: string }[] }) { return <section className="surface-card"><p className="eyebrow">{title}</p><div className="mt-5 space-y-2">{records.length ? records.map((record) => <div key={record.id} className="rounded-xl border border-[#e3ece7] p-3"><p className="text-xs font-bold text-[#35564a]">{record.title}</p><p className="mt-1 text-[11px] text-[#789087]">{record.detail}</p></div>) : <Empty message="Project records will appear here." />}</div></section>; }
function Empty({ message }: { message: string }) { return <div className="rounded-xl border border-dashed border-[#d6e3dc] bg-[#fbfcfa] p-4 text-xs text-[#789087]">{message}</div>; }
